import type { Metadata } from "next";
import "@/styles/project-ui.scss";

export const metadata: Metadata = {
  title: "Compose Stack Next WebApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>{children}</body>
    </html>
  );
}
