import type { Metadata } from "next";

import "@/styles/project-ui.scss";
import { MainNav } from "@/apps/layout/components/main-nav/MainNav";

export const metadata: Metadata = {
  title: "Compose Stack Next WebApp",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head />
      <body>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
